[project]
name = "drop2beets"
version = "2.1.0"
description = "Import singles to Beets as soon as they are dropped in a folder"
authors = [
    { name = "Martin Kirchgessner", email = "martink@gresille.org" },
]
license = "WTFPL"
readme = "README.md"
requires-python = ">=3.10,<4"
homepage = "https://github.com/martinkirch/drop2beets"
repository = "https://github.com/martinkirch/drop2beets.git"
keywords = ["watch", "beets", "music", "import"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Multimedia :: Sound/Audio"
]
dependencies = [
    "beets (>=2.5.1,<3.0.0)",
    "confuse (>=2.1.0)",
    "watchdog (>=6.0.0,<7.0.0)"
]

[dependency-groups]
dev = [
    "mypy (>=1.19.1)",
    "pytest (>=9.0.1,<10.0.0)",
    "pytest-cov",
    "ruff (>=0.6.4)"
]

[tool.poetry]
packages = [
    { include = "beetsplug" },
    { include = "drop2beets" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = """
--cov=beetsplug
--cov-report=xml:.reports/coverage.xml
--cov-report=html:.reports/html
--cov-branch
--cov-context=test
"""
pythonpath = [
  "."
]

[tool.ruff]
target-version = "py310"
line-length = 80

[tool.ruff.lint]
select = [
    # "ARG", # flake8-unused-arguments
    # "C4", # flake8-comprehensions
    "E", # pycodestyle
    "F", # pyflakes
    # "B", # flake8-bugbear
    "G", # flake8-logging-format
    "I", # isort
    "ISC", # flake8-implicit-str-concat
    "N", # pep8-naming
    "PT", # flake8-pytest-style
    # "RUF", # ruff
    "UP", # pyupgrade
    "TCH", # flake8-type-checking
    "W", # pycodestyle
]
ignore = [
    "S102",   # exec() is intentional for on_item callbacks
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pycodestyle]
max-line-length = 88

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "csv"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["cached_classproperty"]
extend-ignore-names = ["assert*", "cached_classproperty"]
